# Generated by Django 4.2.3 on 2023-07-20 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=-1)),
                ('voter', models.ManyToManyField(related_name='voter_movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
